apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: {{ .Auth.InstanceName }}
  namespace: {{ .Auth.Namespace }}
spec:
  authConfigLabelSelectors: {{ .Auth.AuthConfigSelector}}
  clusterWide: true
  listener:
    tls:
      enabled: false
  oidcServer:
    tls:
      enabled: false
