apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: {{ .AuthProviderName }}
  namespace: {{ .AuthNamespace }}
spec:
  authConfigLabelSelectors: {{ .AuthConfigLabelSelectors}}
  clusterWide: true
  listener:
    tls:
      enabled: false
  oidcServer:
    tls:
      enabled: false
