apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: {{ .ControlPlane.Name }}
  namespace: {{ .ControlPlane.Namespace }}
spec:
  techPreview:
    meshConfig:
      extensionProviders:
      - name: {{ .Auth.ProviderName }}
        envoyExtAuthzGrpc:
          service: {{ .Auth.InstanceName }}-authorino-authorization.{{ .Auth.Namespace }}.svc.cluster.local
          port: 50051
