apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: knative-ingress-gateway
  namespace: knative-serving
spec:
  selector:
    knative: ingressgateway
  servers:
    - hosts:
        - '{{ .Serving.KnativeIngressDomain }}'
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: {{ .Serving.KnativeCertificateSecret }}
        mode: SIMPLE
